### ISSUE TITLE
[change] Remove deprecated receive API URL

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#101]
Remove the deprecated `/receive/{id}` URL and its related deprecation warning.

See https://github.com/openwisp/openwisp-network-topology/pull/79 and https://github.com/openwisp/openwisp-network-topology/issues/62 for more info.

**Comment by sankha555** [comment]
Hello @nemesisdesign ,
Can I please take this issue to work upon if it is open for contribution?

**Comment by devkapilbansal** [comment]
> Hello @nemesisdesign ,
> Can I please take this issue to work upon if it is open for contribution?

Sure @sankha555 you can work on this issue if you want
