### ISSUE TITLE
[change] Remove redundant code for checking view permissions

### ISSUE THREAD

**Issue by ManishShah120** [openwisp/openwisp-network-topology#111]
https://github.com/openwisp/openwisp-network-topology/blob/3c3404748a9ecab65f3f4a389f94d2c75fbde732/openwisp_network_topology/api/views.py#L31-L52

I guess, this portion of code does the same thing as what we did recently in this PR https://github.com/openwisp/openwisp-users/pull/251

So, will it not better if we simply import it from there?

**Comment by nemesisdesign** [comment]
> https://github.com/openwisp/openwisp-network-topology/blob/3c3404748a9ecab65f3f4a389f94d2c75fbde732/openwisp_network_topology/api/views.py#L31-L52
> 
> I guess, this portion of code does the same thing as what we did recently in this PR [openwisp/openwisp-users#251](https://github.com/openwisp/openwisp-users/pull/251)
> 
> So, will it not better if we simply import it from there?

This code was added before we introduced https://github.com/openwisp/openwisp-users/pull/251 so yes, it will have to be updated.
