### ISSUE TITLE
[change] Fix visualizer quirks with big topologies

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#164]
When the topology is big, the initial animation is too long, moreover, dragging the nodes causes the long animation to start again, making the graph unusable.

In my testing, I found out that the following works to get rid of the animation issue:

```javascript
graphConfig: {
  series: {
    force: {
      layoutAnimation: false,
    },
    draggable: false
  }
}
```

I guess that for any graph which has more than 20 nodes we can apply these settings.

I believe we have to fetch the JSON data in a separate request, count how many nodes there are and based on that supply this additional config.

If there's more than 50 nodes, I would also supply `edgeLength: 250` to the force layout settings.

**Comment by totallynotvaishnav** [comment]
> I guess that for any graph which has more than 20 nodes we can apply these settings.
> 
> I believe we have to fetch the JSON data in a separate request, count how many nodes there are and based on that supply this additional config.
> 
> If there's more than 50 nodes, I would also supply `edgeLength: 250` to the force layout settings.

I think it is better to do this in the netjsongraph itself. What do you think?

**Comment by nemesisdesign** [comment]
> > I guess that for any graph which has more than 20 nodes we can apply these settings.
> > I believe we have to fetch the JSON data in a separate request, count how many nodes there are and based on that supply this additional config.
> > If there's more than 50 nodes, I would also supply `edgeLength: 250` to the force layout settings.
> 
> I think it is better to do this in the netjsongraph itself. What do you think?

As discussed via IM, at the moment it's safer to implement and iterate this here, if we get to a satisfactory result which we are 100% sure makes sense to implement as default in netjsongraph.js we will follow up.
