### ISSUE TITLE
[docs] Add documentation for the ZeroTier parser

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp-network-topology#192]
We need to add documentation for the `ZeroTier` parser, which explains how to generate a topology from the data received from multiple devices.

**Dependencies**
- [x] https://github.com/openwisp/openwisp-network-topology/issues/135

**Comment by praptisharma28** [comment]
Hey @Aryamanz29 , can I work on this?

**Comment by Aryamanz29** [comment]
Hi @praptisharma28, thanks for showing interest! However, this issue has already been completed under the project ["GSoC'23 -- Adding Support For ZeroTier"](https://github.com/orgs/openwisp/projects/36). We forgot to close this. Meanwhile, you can pick some **'good first issues'** from the [OpenWISP contributor board](https://github.com/orgs/openwisp/projects/3) for contribution :)
