### ISSUE TITLE
Fix unusual fails of travis builds

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/openwisp-network-topology#28]
We see that a test by the name,
`test_multiple_receive_remove(openwisp_network_topology.tests.test_topology.TestTopology)` fails unusually in the travis builds. There is a need to investigate and fix it.

**Comment by rohithasrk** [comment]
The links to build logs are https://travis-ci.org/openwisp/openwisp-network-topology/builds/343952716?utm_source=github_status&utm_medium=notification and https://travis-ci.org/openwisp/openwisp-network-topology/jobs/343952718

**Comment by TheOneAboveAllTitan** [comment]
I'll like to work on this issue, can someone please guide me a little?

**Comment by nemesisdesign** [comment]
@TheOneAboveAllTitan you should follow the steps in the README to run tests.

Run tests many times, the issue should show up at some point.

**Comment by nemesisdesign** [comment]
I think this is the cause of this issue: https://github.com/openwisp/django-netjsongraph/issues/84

**Comment by pawelplsi** [comment]
I think it'll be fixed by https://github.com/openwisp/django-netjsongraph/pull/105

**Comment by nemesisdesign** [comment]
Fixed downstream. :+1:
