### ISSUE TITLE
Add default permissions for operators

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#29]
**Reserved for GCI**

Now that https://github.com/openwisp/openwisp-users/pull/40 is ready  we should enable operators to manage the following objects:

- Link
- Node

While these objects should be read-only (will only work for django >= 2.1):

- Topology

Administrators instead will be able to manage everything.

Similar PRs done in other modules:

- https://github.com/openwisp/openwisp-users/pull/40
- https://github.com/openwisp/openwisp-controller/pull/57

**Comment by ppabcd** [comment]
i'll take this issues.
