### ISSUE TITLE
Revise django-model-utils’s version constraint to remove the potential dependency conflicts

### ISSUE THREAD

**Issue by NeolithEra** [openwisp/openwisp-network-topology#38]
Hi, as shown in the following full dependency graph of **_openwisp-network-topology_**, direct dependency _**django-netjsongraph(required: >=0.4.2,<0.5.0, installed 0.4.3)**_ depends on _**django-model-utils (no version constraint)**_， while the installed version of **_openwisp-utils_**(0.2.2) requires _**django-model-utils>=3.1.2,<3.3.0**_.

According to Pip's “first found wins” installation strategy, _**django-model-utils 3.2.0**_ is the actually installed version.  

Although the first found package version _**django-model-utils 3.2.0**_ just satisfies the later dependency constraint (_**django-model-utils>=3.1.2,<3.3.0**_), it will lead to a build failure once developers release a  _**appdirs**_ whose version number is greater than 3.3.0.

### Dependency tree--------
```
openwisp-network-topology -0.2.1
| +-django-netjsongraph(version range:>=0.4.2,<0.5.0)
| | +-django(version range:>=1.11,<2.1)
| | +-djangorestframework(version range:>=3.3,<3.8)
| | +-django-model-utils(version range:*)
| | +-netdiff(version range:>=0.6.0,<0.7)
| | +-openwisp-utils(version range:>=0.2,<0.3)
| | | +-django-model-utils(version range:>=3.1.2,<3.3.0)
| | +-jsonfield(version range:*)
| | +-six(version range:*)
| +-openwisp-users(version range:>=0.1.8,<0.2)
| | +-django-organizations(version range:>=1.0.0,<1.2.0)
| | +-django-extensions(version range:>=1.7.5,<2.2)
| | +-django-allauth(version range:>=0.35.0,<0.37.0)
| +-openwisp-utils(version range:>=0.2,<0.3)
| | +-django-model-utils(version range:>=3.1.2,<3.3.0)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

Reverse the declaration order of _**openwisp-utils**_ and _**django-netjsongraph**_.
Then, according to “first found wins” strategy, this conflict can be removed, as pip will install django-model-utils>=3.1.2, <3.3.0.


@rohithasrk     May I pull a request to solve this issue?

**Comment by nemesisdesign** [comment]
Should be fixed.
