### ISSUE TITLE
[network-topology] Organization field in Node and Link redundant

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#54]
Organization field in `Node` and `Link` is redundant.

We should remove the field and make sure the multi-tenant admin can still work.

Similar to https://github.com/openwisp/openwisp-ipam/issues/28.

**Update**: due to #107, it may be possible that the organization field in node and link may be useful to make sure nodes and links are always assigned to the right org.

**Comment by nemesisdesign** [comment]
It may be related to https://github.com/openwisp/openwisp-network-topology/issues/107.

**Comment by pandafy** [comment]
Organization field in Snapshot is also redundant. A snapshot cannot have organization different from the topology.

**Comment by nemesisdesign** [comment]
> Organization field in Snapshot is also redundant. A snapshot cannot have organization different from the topology.

You're right, this is easier to fix, can you create an issue for that please?

**Comment by nemesisdesign** [comment]
Closing this one as we understood it's useful to have the org field on Node and Link, I created an issue for the snapshot model: #146.
