### ISSUE TITLE
[network-topology][notifications] Add openwisp-notifications as an optional dependency.

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-network-topology#55]
Create a sub app for notifications. Notifications should be generated for following events
- [ ] When link status changes
- [ ] When a new node get added in topology

Depends on https://github.com/openwisp/openwisp-notifications/issues/1

**Comment by nemesisdesign** [comment]
Let's close this for now and focus on the other issues. If it becomes relevant I'll reopen.
