### ISSUE TITLE
[gsoc2020]  Merge django-netjsongraph into openwisp-network-topology

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-network-topology#58]
- [x] Merge django-netjsongraph into openwisp-network-topology
- [x] Migrate the django settings of each module so that the naming is consistent. (eg: `NETJSONCONFIG_[SETTING_NAME]` -> `OPENWISP_CONTROLLER_[SETTING_NAME]`)
- [x] Keep backward compatibility for setting names but log a warning to encourage the users to upgrade the name of the setting to the new name.
- [x] Implement as easy as possible extensibility of Django modules.
- [x] Add sample_app for testing extensibility with some changes.
- [x] Update documentation

**Comment by nemesisdesign** [comment]
@atb00ker the issue description has an issue, it mentions `netjsonconfig` and `openwisp_controller` but it should mention `netjsongraph` and `openwisp_network_topology` I think.

**Comment by atb00ker** [comment]
@nemesisdesign you mean in second checkbox right? That's just an example I added about what change is required for that checkbox -- I could change it in all the PRs if you want, but it's all the same for my understanding really! :smile:
