### ISSUE TITLE
[api] NetworkGraphSerializer.Meta.model

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#61]
@atb00ker, can you please take care of this when introducing swappable and merging? https://github.com/openwisp/openwisp-network-topology/commit/a0c5d59e009b32fcf7355dc02aed00473dd3f299

**Comment by atb00ker** [comment]
How do I test this change? 
I tried the django-rest-swagger, I can't find a difference with or without these lines, where should I be looking?
