### ISSUE TITLE
[admin] Add OpenWISP admin theme

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/openwisp-network-topology#7]
Add the customised admin theme of OpenWISP to the application. As implemented in openwisp-controller.

**Comment by nemesisdesign** [comment]
@rohithasrk it's time to start separating shared features and utilities of the different openwisp packages into a new package.

I don't know when I can work on this but I want to do it soon: let's mark it as lower priority.

**Comment by rohithasrk** [comment]
Yeah @nemesisdesign You are right. There is a lot of shared code. It should be done.

**Comment by rohithasrk** [comment]
Will be added to openwisp-utils. https://github.com/openwisp/openwisp-utils
