### ISSUE TITLE
[change] Require authentication for views

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-network-topology#77]
Right now the views (visualizer and API) are available to anyone.
This was done mainly because this module was used by community owned mesh network.

But now this module is also used to monitor private networks and we need to close it by default.
In the API we can use `IsAuthenticated`, `DjangoPermissions` and we should check the organization as well.
In the visualizer views we should use an equivalent mechanism

It should still be possible to disable auth via settings, eg: `OPENWISP_NETWORK_TOPOLOGY_API_AUTH_REQUIRED`.

**Comment by NoumbissiValere** [comment]
@nemesisdesign concerning Organization checks, should we just check if user is member of object's organization or manager?

**Comment by nemesisdesign** [comment]
Only member, the django permission check will do the rest.
@NoumbissiValere this is kind of blocked by https://github.com/openwisp/openwisp-users/pull/151, but maybe you can use that code anyway (temporarily install that branch in travis) since the pending requested changes are mostly cosmetic and documentation related. Please coordinate with @atb00ker.

**Comment by NoumbissiValere** [comment]
ok @nemesisdesign

**Comment by atb00ker** [comment]
I'll try to get to https://github.com/openwisp/openwisp-users/pull/151 next week! :smile:

**Comment by NoumbissiValere** [comment]
Ok @atb00ker

**Comment by atb00ker** [comment]
@NoumbissiValere 
https://github.com/openwisp/openwisp-users/pull/151 is ready and https://github.com/openwisp/openwisp-radius/pull/137 is it's example usage.

**Comment by NoumbissiValere** [comment]
Thank you @atb00ker :smile: I will finish this work ASAP :smile:
